# You can edit this code and run it right here in the browser!
# First we'll import some turtles and shapes: 
from turtle import *
from shapes import *
import time


# Create a turtle named Tommy:
tommy = Turtle()
tommy.shape("turtle")
tommy.speed(100)

# Draw three circles:
draw_circle(tommy, "black", 45, 37, 17)
draw_circle(tommy, "peachpuff", 50, 25, 0)
tommy.begin_fill()
tommy.goto(-25,0)
tommy.circle(30,-180)
tommy.goto(25,50)
tommy.end_fill()
tommy.fillcolor("firebrick")
tommy.goto(-25,0)
tommy.begin_fill()
tommy.circle(-10)
tommy.end_fill()
tommy.color("black")
tommy.goto(-25,0)
tommy.circle(-10)
draw_circle(tommy, "black", 13, 0, 70)
draw_circle(tommy, "white", 5, 0, 63)
draw_circle(tommy, "black", 13, 40, 70)
draw_circle(tommy, "white", 5, 40, 63)
tommy.penup()
tommy.color("black")
tommy.goto(15,73)
tommy.pendown()
tommy.right(90)
tommy.circle(13, 180)
tommy.penup()
tommy.goto(28, 70)
tommy.pendown()
tommy.circle(13, -180)
tommy.penup()
tommy.goto(-3, 91)
tommy.pendown()
tommy.begin_fill()
tommy.circle(3,-360)
tommy.end_fill()
tommy.goto(10, 100)
tommy.begin_fill()
tommy.circle(3)
tommy.goto(7,105)
tommy.goto(-5, 96)
tommy.goto(-3, 91)
tommy.goto(10, 100)
tommy.end_fill()
tommy.penup()
draw_circle(tommy, "black", 3, 20, 91)
tommy.begin_fill()
tommy.goto(10, 102)
tommy.goto(7, 97)
tommy.goto(16, 88)
tommy.end_fill()

draw_circle(tommy,"black", 3, 35, 91)
tommy.pendown()
tommy.begin_fill()
tommy.goto(45,100)
tommy.circle(3)
tommy.goto(35, 100)
tommy.goto(28, 91)
tommy.end_fill()
tommy.penup()
tommy.goto(55, 91)
tommy.begin_fill()
tommy.pendown()
tommy.circle(3)
tommy.goto(49, 91)
tommy.goto(40, 100)
tommy.end_fill()
tommy.goto(43, 100)

tommy.penup()
draw_circle(tommy, "peachpuff", 15, 97, 30)
tommy.penup()
tommy.goto(0, -100)