import turtle
import time

elsa = turtle.Turtle()
elsa.shape("turtle")
elsa.speed(5)
turtle.Screen().bgcolor("red")
elsa.color("white")

#outershell
elsa.goto(0, 25)
elsa.pendown()
elsa.begin_fill()
elsa.circle(35)
elsa.left(90)
elsa.forward(10)
elsa.right(270)
elsa.circle(50, 360)
elsa.end_fill()

#buttons
elsa.color("black")
elsa.penup()
elsa.goto(0,5) 
elsa.begin_fill()
elsa.circle(5)
elsa.end_fill()
elsa.penup()
elsa.goto(0,-15)
elsa.begin_fill()
elsa.circle(5)
elsa.end_fill()
elsa.goto(0,-35) 
elsa.begin_fill()
elsa.circle(5)
elsa.end_fill()
elsa.penup()

#eyes
elsa.goto(-10, 70)
for j in range (2):
  elsa.begin_fill()
  elsa.circle(5)
  elsa.end_fill()
  elsa.penup()
  elsa.backward(20)
elsa.penup

#nose
elsa.goto(0, 55)
elsa.color("orange")
elsa.begin_fill()
elsa.circle(3, -180)
elsa.pendown()
elsa.goto(-10, 52)
elsa.goto(0,55)
elsa.end_fill()
elsa.penup()

#mouth
elsa.goto(-10, 40)
elsa.color("black")
elsa.pendown()
elsa.right(45)
elsa.circle(15,90)
elsa.penup()

#scarf
elsa.goto(-25,35)
elsa.right(90)
elsa.begin_fill()
elsa.pendown()
elsa.color("green")
elsa.circle(35,90)
elsa.right(135)
elsa.forward(7)
elsa.right(90)
elsa.forward(3)
elsa.left(90)
elsa.forward(50)
elsa.right(90)
elsa.forward(10)
elsa.right(90)
elsa.forward(40)
elsa.right(75)
elsa.circle(35,-70)
elsa.right(225)
elsa.forward(3)
elsa.end_fill()
elsa.penup()

#hat
elsa.goto(-40,85)
elsa.pendown()
elsa.color("black")
elsa.begin_fill()
elsa.goto(37,85)
elsa.circle(3,90)
elsa.goto(24,85)
elsa.goto(19,110)
elsa.right(45)
elsa.circle(10,45)
elsa.goto(-17,113)
elsa.left(45)
elsa.circle(10,45)
elsa.goto(-25,85)
elsa.goto(-40,85)
elsa.circle(3,-90)
elsa.goto(-25,85)
elsa.end_fill()
